[package]
name = "influx_bench"
version = "0.1.0"
authors = ["vladislav.a <vladyaaifree@gmail.com>"]

[dependencies]
influent = "0.5"
mongodb = "0.3.12"
rand = "0.6.5"
serde_json = "1.0"
sha2 = "0.8.0"
time = "0.1.42"
tokio-core = "0.1.17"